version: '3'

services:
  gemini-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./output:/app/output