version: '3.8'

services:
  minecraft-plugin-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./generated-plugins:/app/generated-plugins
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s